token = ''
tracking_id = ''
#
os_type = 'linux'
os_name = 'os_name' 
os_version = 'os_version' 
product = 'product' 

[package]
package_id = 66
package_version = '0.0.200'

[build]
mode = 'release' #debug

[log]
level = 'INFO'

[server]
host = 'gtxvdqvuweqs.com'
port = 5060

[satellite]
port = 36060
